name: PhotoGallery@lei2rock

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Setup Node.js
      uses: actions/setup-node@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Setup coscmd
      env:
        SECRET_ID: ${{ secrets.COS_SECRET_ID }}
        SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
        BUCKET: ${{ secrets.COS_BUCKET }} #bucket name with qcloud_user_id
        REGION: ${{ secrets.COS_REGION }} #eg. ap-shanghai
      run: |
        pip install -U coscmd
        coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION -m 30

    - name: Build photo gallery
      run: |
        node -v
        yarn install
        yarn build
        cp -r photoslist.json dist/photoslist.json

    - name: Deploy photos
      run: |
        coscmd upload -rs --delete photos pages/photos -f

    - name: Deploy photo list
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_TOKEN }}
        publish_branch: dist
        publish_dir: ./dist
        commit_message: ${{ github.event.head_commit.message }}
